### ISSUE TITLE
New MLB url formatting causes error

### ISSUE THREAD

**Issue by Mpellet771** [cpsievert/XML2R#6] opened 2018-02-17 05:02 UTC
Thank you for writing this package. However, for 2017 on, the url can't be resolved if the base url has the slash after the DAy_## section, like this:

http://gd2.mlb.com/components/game/mlb/year_2017/month_06/day_14/

Using that last slash gets you an error code. It must be removed from the base url and added to the gid url.

**Comment by cpsievert** [comment] 2018-02-20 15:19
Duplicate of https://github.com/cpsievert/pitchRx/issues/59

**Closed by cpsievert** 2018-02-20 15:19 UTC
